database:
  datasource:
    postgre:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: root
      url: jdbc:postgresql://localhost:5432/postgres
    mySql:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306
